### ISSUE TITLE
npm ERR! code EINTEGRITY integrity checksum failed when using sha1

### ISSUE THREAD

**Issue by davidpodhola** [felixrieseberg/npm-windows-upgrade#113]
PS C:\Windows\system32> npm install --global --production npm-windows-upgrade
npm ERR! code EINTEGRITY
npm ERR! sha1-KqEH8UKvQSHRRWWdRPUIMJYeaZo= integrity checksum failed when using sha1: wanted sha1-KqEH8UKvQSHRRWWdRPUIMJ
YeaZo= but got sha1-RzK1EJBw5vdJt2q2z0uiIhlMsEo=. (13270 bytes)

**Comment by felixrieseberg** [comment]
This is a server error (the package downloaded somehow doesn't match the one we expected). Simply trying again should fix this.

Thanks for the report though!

**Comment by liliom55** [comment]
Still get error with npm version 5.3.0 on Windows 10 after running 
```
The following solved it for me:
rm -rf node_modules
rm package-lock.json
rm -rf ~/.npm
npm install --update-binary --no-shrinkwrap

```
Error:
```

16614 verbose type OperationalError
16615 verbose stack Error: sha1-mnHEh0chjrylHlGmbaaCA4zct78= integrity checksum failed when using sha1: wanted sha1-mnHEh0chjrylHlGmbaaCA4zct78= but got sha1-w9WI/Kl27QUwjH4VJ0y2IbX+JAI=. (5078665 bytes)
16615 verbose stack     at Transform.on (C:\Users\...\AppData\Roaming\npm\node_modules\npm\node_modules\ssri\index.js:275:19)
16615 verbose stack     at emitNone (events.js:91:20)
16615 verbose stack     at Transform.emit (events.js:185:7)
16615 verbose stack     at endReadableNT (_stream_readable.js:974:12)
16615 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:80:11)
16615 verbose stack     at process._tickCallback (internal/process/next_tick.js:104:9)
16616 verbose cwd C:\Users\...\Documents\metaformaUI
16617 verbose Windows_NT 10.0.15063
16618 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\...\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--update-binary" "--no-shrinkwrap"
16619 verbose node v6.11.2
16620 verbose npm  v5.3.0
16621 error code EINTEGRITY
16622 error sha1-mnHEh0chjrylHlGmbaaCA4zct78= integrity checksum failed when using sha1: wanted sha1-mnHEh0chjrylHlGmbaaCA4zct78= but got sha1-w9WI/Kl27QUwjH4VJ0y2IbX+JAI=. (5078665 bytes)

```

**Comment by ravindralande** [comment]
npm -v  5.*
node -v 8.*
npm set registry https://registry.npmjs.org/
yarn install
fixed this issue for me

**Comment by Naliaka** [comment]
Thanks it resolve the issue!

**Comment by NeerajSachdeva** [comment]
Although retrying might have worked for you, but if somebody still faces such issue then try below suggestions:

npm cache clean --force
OR
Deleting npm and npm-cache folders in Users%username%\AppData\Roaming (windows 7) and running npm install
OR
Update npm by via npm i -g npm
OR
Delete package-lock.json
OR
npm cache verify
OR
npm cache clean

**Comment by VanessaOrtiz30** [comment]
As a workaround, follow the below steps:
•	Go to the project directory
•	Remove the node_modules directory: rm -rf node_modules.
•	Remove package-lock.json file: rm package-lock.json
•	Clear the cache: npm cache clean --force
•	Run npm install --verbose
If after following the above steps still the issue exists then please provide us the output of installation command with --verbose.

**Comment by FE-xiaoJiang** [comment]
> Although retrying might have worked for you, but if somebody still faces such issue then try below suggestions:
> 
> npm cache clean --force
> OR
> Deleting npm and npm-cache folders in Users%username%\AppData\Roaming (windows 7) and running npm install
> OR
> Update npm by via npm i -g npm
> OR
> Delete package-lock.json
> OR
> npm cache verify
> OR
> npm cache clean

worked for me,well done

**Comment by Chizaram-Igolo** [comment]
> As a workaround, follow the below steps:
> •	Go to the project directory
> •	Remove the node_modules directory: rm -rf node_modules.
> •	Remove package-lock.json file: rm package-lock.json
> •	Clear the cache: npm cache clean --force
> •	Run npm install --verbose
> If after following the above steps still the issue exists then please provide us the output of installation command with --verbose.

Thanks, it fixed it. I find this kind of weird that running this with the --verbose flag would fix this issue as I had thought that it (--verbose) was more of a diagnostic tool. 

I hope this issue will be addressed in future releases of NPM.

**Comment by irfiacre** [comment]
Am trying to run `npm i swagger` but it returns
`sha1-pDFsyw1Ap30w2t+R8PTbfkdflIo= integrity checksum failed when using sha1: wanted sha1-pDFsyw1Ap30w2t+R8PTbfkdflIo= but got sha512-fpi4TmjzlFcS7KklxlvfQI5Bi+KAfoh3xv3r6SO5oKCMC5Fc6BBImJWJpEACyKhsSt3biAtwn3hFlgMeQze5xw== sha1-L6K5CPbr4CS/LYCixit2seOAoVc=.`

any help would be appreciated. thanks

**Comment by wdegraaf-travel1** [comment]
For those that tried everything and nothing worked - on my machine updating node.js to the latest LTS release was the only thing that fixed the EINTEGRITY issue.  Apparently I had been forgetting to update my node installation on Windows for the past year.

**Comment by panchal99** [comment]
> As a workaround, follow the below steps:
> • Go to the project directory
> • Remove the node_modules directory: rm -rf node_modules.
> • Remove package-lock.json file: rm package-lock.json
> • Clear the cache: npm cache clean --force
> • Run npm install --verbose
> If after following the above steps still the issue exists then please provide us the output of installation command with --verbose.

Thanks, it fixed it. I find this kind of weird that running this with the --verbose flag would fix this issue as I had thought that it (--verbose) was more of a diagnostic tool.

**Comment by moodboom** [comment]
The --verbose flag didn't fix it, all the prior cache cleanup did.  :-)

**Comment by Salman2301** [comment]
LTS or deleting npm-cache folder in the appData/roaming fixed it

**Comment by galibgaurav** [comment]
For me this problem got solved by doing registry setting as for me registry setting was empty: 
 npm config set registry "https://registry.npmjs.org/"

**Comment by insookwa** [comment]
This worked  for me . 
opened the repo in cmd and ran 
npm cache verify 
npm install

**Comment by kcamas** [comment]
Encountering this error as well when running `npm install,`
```
npm ERR! code EINTEGRITY
npm ERR! sha512-FCEhQ/4rE1zYv9rYXJw/msRqsnmlje5jHP6huWeBZ704jUTy02c5AZyWujpMR1ax6mVw9NyJMfuK2CMDWVIfgA== integrity checksum failed when using sha512: wanted sha512-FCEhQ/4rE1zYv9rYXJw/msRqsnmlje5jHP6huWeBZ704jUTy02c5AZyWujpMR1ax6mVw9NyJMfuK2CMDWVIfgA== but got sha512-vhZ18zh5iZ00XRB19T5BHtkv9OpDMA9Cj+jhoqKryIwRxXb8L0kZUt+XLHFSxaV/mM2Zd9sEB4S3IwIlqIDQkA==. (15575 bytes)
```

tried doing the ff:
1. Clean npm install (remove node_modules + package-lock.json)
2. npm cachce clean --force && npm cache verify
3. npm install --verbose

but nothing has worked. Tried almost everything listed on forums/threads but all unsuccessful. :/

**Comment by blackrock33** [comment]
Finally, I use yarn to install instead of npm temporarily jump this issue

**Comment by AlexKirilov** [comment]
I have the same issue and tryed everything into the forums. I am using verdaccio to maintain my internal libraries. All my projects are building locally, but when I use TeamCity on a server it fails with the same error. Everything was working perfectly till last  Friday (18/09/2020)

I tryed the options provided above, but the result is the same. 

I am attching my npm install --verbose details here:
If someone has an idea what can be the issue?

Project is created with Angular 9 .

PowerShell  angu;ar installation error:
![image](https://user-images.githubusercontent.com/5669746/93758258-fee6eb00-fbff-11ea-8451-1d1273cfc532.png)

Verbosee installation logs

2 info using npm@6.14.8
3 info using node@v12.18.4
4 verbose npm-session 984938faefe3b485
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall cgi-x-wif@0.0.0
7 info lifecycle cgi-x-wif@0.0.0~preinstall: cgi-x-wif@0.0.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 13ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 4ms
16 silly install loadAllDepsIntoIdealTree
17 http fetch GET 200 http://localhost:4873/@types%2fjasminewd2 323ms
18 http fetch GET 200 http://localhost:4873/codelyzer 329ms
19 http fetch GET 200 http://localhost:4873/jasmine-core 339ms
20 silly pacote range manifest for @types/jasminewd2@~2.0.3 fetched in 350ms
21 http fetch GET 200 http://localhost:4873/@types%2fjasmine 355ms
22 silly pacote range manifest for codelyzer@^5.1.2 fetched in 357ms
23 silly pacote range manifest for jasmine-core@~2.99.1 fetched in 362ms
24 silly pacote range manifest for @types/jasmine@~2.8.8 fetched in 433ms
25 http fetch GET 200 http://localhost:4873/@webcomponents%2fwebcomponentsjs 437ms
26 silly pacote range manifest for @webcomponents/webcomponentsjs@^2.2.10 fetched in 452ms
27 http fetch GET 200 http://localhost:4873/@angular%2fcompiler-cli 658ms
28 silly pacote range manifest for @angular/compiler-cli@^9.0.7 fetched in 676ms
29 http fetch GET 200 http://localhost:4873/@angular-devkit%2fbuild-angular 746ms
30 http fetch GET 200 http://localhost:4873/@angular%2flanguage-service 758ms
31 silly pacote range manifest for @angular-devkit/build-angular@~0.900.7 fetched in 793ms
32 silly pacote range manifest for @angular/language-service@~9.0.7 fetched in 787ms
33 http fetch GET 200 http://localhost:4873/jasmine-spec-reporter 438ms
34 http fetch GET 200 http://localhost:4873/karma-chrome-launcher 434ms
35 http fetch GET 200 http://localhost:4873/@angular%2fcli 814ms
36 silly pacote range manifest for @angular/cli@^9.0.7 fetched in 837ms
37 http fetch GET 200 http://localhost:4873/karma-coverage-istanbul-reporter 470ms
38 http fetch GET 200 http://localhost:4873/karma-chrome-launcher/-/karma-chrome-launcher-2.2.0.tgz 106ms
39 http fetch GET 200 http://localhost:4873/jasmine-spec-reporter/-/jasmine-spec-reporter-4.2.1.tgz 120ms
40 http fetch GET 200 http://localhost:4873/karma-jasmine 472ms
41 silly pacote range manifest for karma-coverage-istanbul-reporter@~2.0.1 fetched in 498ms
42 silly pacote range manifest for karma-chrome-launcher@~2.2.0 fetched in 568ms
43 silly pacote range manifest for jasmine-spec-reporter@~4.2.1 fetched in 584ms
44 silly pacote range manifest for karma-jasmine@~1.1.2 fetched in 490ms
45 http fetch GET 200 http://localhost:4873/karma-jasmine-html-reporter 332ms
46 http fetch GET 200 http://localhost:4873/karma-teamcity-reporter 294ms
47 http fetch GET 200 http://localhost:4873/karma-jasmine-html-reporter/-/karma-jasmine-html-reporter-0.2.2.tgz 68ms
48 http fetch GET 200 http://localhost:4873/protractor 303ms
49 silly pacote range manifest for karma-jasmine-html-reporter@^0.2.2 fetched in 423ms
50 http fetch GET 200 http://localhost:4873/ts-node 267ms
51 silly pacote range manifest for protractor@~5.4.0 fetched in 326ms
52 http fetch GET 200 http://localhost:4873/@types%2fnode 1112ms
53 silly pacote range manifest for ts-node@~7.0.0 fetched in 393ms
54 http fetch GET 200 http://localhost:4873/karma-teamcity-reporter/-/karma-teamcity-reporter-1.1.0.tgz 165ms
55 silly pacote range manifest for @types/node@^12.11.1 fetched in 1243ms
56 silly pacote range manifest for karma-teamcity-reporter@^1.1.0 fetched in 489ms
57 http fetch GET 200 http://localhost:4873/tslint 360ms
58 http fetch GET 200 http://localhost:4873/karma 953ms
59 silly pacote range manifest for tslint@~5.11.0 fetched in 438ms
60 silly pacote range manifest for karma@^4.0.1 fetched in 1020ms
61 http fetch GET 200 http://localhost:4873/@angular-devkit%2fbuild-webpack 519ms
62 http fetch GET 200 http://localhost:4873/@angular-devkit%2fcore 522ms
63 silly pacote range manifest for @angular-devkit/build-webpack@^0.900.7 fetched in 610ms
64 silly pacote range manifest for @angular-devkit/core@^9.0.7 fetched in 606ms
65 http fetch GET 200 http://localhost:4873/@angular-fsl%2fmessage-handler 282ms
66 http fetch GET 200 http://localhost:4873/@angular-devkit%2fschematics 506ms
67 http fetch GET 200 http://localhost:4873/@angular-fsl%2fmessage-handler/-/message-handler-1.10.9-12.tgz 60ms
68 silly pacote range manifest for @angular-devkit/schematics@^9.0.7 fetched in 560ms
69 silly pacote range manifest for @angular-fsl/message-handler@^1.10.9-12 fetched in 395ms
70 http fetch GET 200 http://localhost:4873/@angular%2fcdk 132ms
71 silly pacote range manifest for @angular/cdk@^9.1.3 fetched in 157ms
72 http fetch GET 200 http://localhost:4873/@angular%2fanimations 177ms
73 silly pacote range manifest for @angular/animations@~9.0.7 fetched in 226ms
74 http fetch GET 200 http://localhost:4873/@angular%2fcompiler 214ms
75 silly pacote range manifest for @angular/compiler@^9.0.7 fetched in 242ms
76 http fetch GET 200 http://localhost:4873/typescript 972ms
77 http fetch GET 200 http://localhost:4873/@angular%2fcommon 329ms
78 http fetch GET 200 http://localhost:4873/@angular-fsl%2ffin-nested-tables 903ms
79 silly pacote range manifest for typescript@~3.7.5 fetched in 1092ms
80 verbose stack Error: sha512-yasB26e+aP7gmKMcVeER7D2MF85IlhKNw3G+zp5Am7K1HVfnP5C6rk04TlOdV57/Jxft4LsFniuR2Pqejd8S5A== integrity checksum failed when using sha512: wanted sha512-yasB26e+aP7gmKMcVeER7D2MF85IlhKNw3G+zp5Am7K1HVfnP5C6rk04TlOdV57/Jxft4LsFniuR2Pqejd8S5A== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes)
80 verbose stack     at Transform.<anonymous> (C:\Users\sa-teamcity-CGiX\AppData\Roaming\npm\node_modules\npm\node_modules\ssri\index.js:328:19)
80 verbose stack     at Transform.emit (events.js:327:22)
80 verbose stack     at endReadableNT (_stream_readable.js:1220:12)
80 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
81 verbose cwd C:\TeamCity\TeamCity\BuildAgentMulder\work\103c13470ade8256\What.If.UI
82 verbose Windows_NT 10.0.14393
83 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\sa-teamcity-CGiX\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbose"
84 verbose node v12.18.4
85 verbose npm  v6.14.8
86 error code EINTEGRITY
87 error sha512-yasB26e+aP7gmKMcVeER7D2MF85IlhKNw3G+zp5Am7K1HVfnP5C6rk04TlOdV57/Jxft4LsFniuR2Pqejd8S5A== integrity checksum failed when using sha512: wanted sha512-yasB26e+aP7gmKMcVeER7D2MF85IlhKNw3G+zp5Am7K1HVfnP5C6rk04TlOdV57/Jxft4LsFniuR2Pqejd8S5A== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes)
88 verbose exit [ 1, true ]

**Comment by terrycoughlan** [comment]
> As a workaround, follow the below steps:
> • Go to the project directory
> • Remove the node_modules directory: rm -rf node_modules.
> • Remove package-lock.json file: rm package-lock.json
> • Clear the cache: npm cache clean --force
> • Run npm install --verbose
> If after following the above steps still the issue exists then please provide us the output of installation command with --verbose.

Hi @VanessaOrtiz30  

I tried the commands above but still get the same issue - here is the output:

npm http fetch GET 200 http://server01:8081/repository/ecomm_npm_group/@babel/plugin-transform-shorthand-properties/-/plugin-transform-shorthand-properties-7.10.4.tgz 3761ms
npm verb stack Error: sha512-PPmu...C6JA== integrity checksum failed when using sha512: wanted sha512-PPmu8e...OzC6JA== but got sha512-ka3c3...b/Fw==. (1940 bytes)
npm verb stack     at Transform.on (C:\Users\xxxxxxxxxx\AppData\Roaming\nvm\v10.16.3\node_modules\npm\node_modules\ssri\index.js:328:19)
npm verb stack     at Transform.emit (events.js:203:15)
npm verb stack     at endReadableNT (_stream_readable.js:1145:12)
npm verb stack     at process._tickCallback (internal/process/next_tick.js:63:19)
npm verb cwd C:\Workspace\angularUpdatedtoLatestVersion\angular9
npm verb Windows_NT 10.0.17763
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbose"
npm verb node v10.16.3
npm verb npm  v6.9.0
npm ERR! code EINTEGRITY
npm ERR! sha512-PPmu....OzC6JA== integrity checksum failed when using sha512: wanted sha512-PPmu8e....zC6JA== but got sha512-ka3c3riF.../Fw==. (1940 bytes)
npm verb exit [ 1, true ]
npm WARN tar invalid entry
npm WARN tar invalid entry
npm WARN tar invalid entry
npm http fetch GET 200 http://server01:8081/repository/ecomm_npm_group/@types/node/-/node-12.12.64.tgz 6941ms
npm http fetch GET 200 http://server01:8081/repository/ecomm_npm_group/@babel/runtime/-/runtime-7.11.2.tgz 9848ms
npm http fetch GET 200 http://server01:8081/repository/ecomm_npm_group/aria-query/-/aria-query-3.0.0.tgz 43859ms
npm http fetch GET 200 http://server01:8081/repository/ecomm_npm_group/caniuse-lite/-/caniuse-lite-1.0.30001146.tgz 130938ms
npm WARN tarball tarball data for @angular/compiler-cli@^9.0.5 (sha512-bbqJ+fbY+...cPTa/YRZ44jpL+5cCzIrg==) seems to be corrupted. Trying one more time.
npm http fetch GET 502 http://server01:8081/repository/ecomm_npm_group/@angular/core/-/core-9.1.12.tgz 440548ms attempt #3
npm timing action:extract Completed in 444025ms
npm http fetch GET 502 http://server01:8081/repository/ecomm_npm_group/ngx-bootstrap/-/ngx-bootstrap-5.6.2.tgz 442704ms attempt #3
npm http fetch GET 502 http://server01:8081/repository/ecomm_npm_group/@angular/common/-/common-9.1.12.tgz 442484ms attempt #3

Any ideas??

**Comment by edencorbin** [comment]
Delete package-lock.json seriously how many times has that solved my problems in node, can anyone explain why it was invented and why we should use it, I ignore it from repos as fast I can, and avoid it like the plague.

**Comment by pabhale2** [comment]
> As a workaround, follow the below steps:
> • Go to the project directory
> • Remove the node_modules directory: rm -rf node_modules.
> • Remove package-lock.json file: rm package-lock.json
> • Clear the cache: npm cache clean --force
> • Run npm install --verbose
> If after following the above steps still the issue exists then please provide us the output of installation command with --verbose.

Thank you It works for me. :)

**Comment by master-tecs** [comment]
Error creating react app

npm ERR! code EINTEGRITY
npm ERR! sha512-1Zh7LjuIoEhIyjkBflSSGzfjuPQwDlghNloppjruOH5bmj9midT9qcNT0tRUZRR04shU9ekrxNy9+UTBrqeBpQ== integrity checksum failed when using sha512: wanted sha512-1Zh7LjuIoEhIyjkBflSSGzfjuPQwDlghNloppjruOH5bmj9midT9qcNT0tRUZRR04shU9ekrxNy9+UTBrqeBpQ== but got sha512-BaGXMLYF+/Tj4P1XV+V9+0mx8YnaTva9NQwTnX4GVB4FyyKlswtSUnqKedrxRI3ZClRoS3sHsRPQO4fLbP2Duw==. (212205 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Abdulwahab\AppData\Roaming\npm-cache\_logs\2021-01-12T18_22_12_992Z-debug.log

**Comment by ajcanelhas** [comment]
npx create-react-app
npm ERR! code EINTEGRITY
npm ERR! sha512-FCEhQ/4rE1zYv9rYXJw/msRqsnmlje5jHP6huWeBZ704jUTy02c5AZyWujpMR1ax6mVw9NyJMfuK2CMDWVIfgA== integrity checksum failed when using sha512: wanted sha512-FCEhQ/4rE1zYv9rYXJw/msRqsnmlje5jHP6huWeBZ704jUTy02c5AZyWujpMR1ax6mVw9NyJMfuK2CMDWVIfgA== but got sha512-bHKSgTioII8PL5oXc3itEhGeXVlAnjBKGZv2HJzt6vecOZVuGgayg3if4OglwXoqEwCqxuQZPrVtC4gSqnpyyw==. (183892 bytes)

**Comment by Ruchit3425** [comment]
C:\Users\Vinod>npm i -g firebase-tools
npm ERR! code EINTEGRITY
npm ERR! path C:\Users\Vinod\AppData\Local\npm-cache\_cacache\content-v2\sha512\89\a6\628bdc303089b6f956e216154eb2042e137c4a73df4f8da2ee6831810ba1eba00faf401dbcdea4a9170bb9d5798ce038da5e5e5b8505bc7af73e769db411
npm ERR! errno EINTEGRITY
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/@types%2fduplexify: Integrity verification failed for sha512-iaZii9wwMIm2+VbiFhVOsgQuE3xKc99PjaLuaDGBC6HroA+vQB283qSpFwu51XmM4DjaXl5bhQW8evc+dp20EQ== (C:\Users\Vinod\AppData\Local\npm-cache\_cacache\content-v2\sha512\89\a6\628bdc303089b6f956e216154eb2042e137c4a73df4f8da2ee6831810ba1eba00faf401dbcdea4a9170bb9d5798ce038da5e5e5b8505bc7af73e769db411)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Vinod\AppData\Local\npm-cache\_logs\2021-07-17T07_16_09_039Z-debug.log
