### ISSUE TITLE
Error trying to install v3.0.0

### ISSUE THREAD

**Issue by dlong500** [felixrieseberg/npm-windows-upgrade#79]
I'm running Win7 x64 and I'm getting an error trying to install v3.0.0.

I tried manually cleaning everything out, and even reinstalling npm itself and still have the problem.  If I manually install v2.3.1 then it works fine.

The error is as follows:

```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "npm-windows-upgrade"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! path C:\Users\<user>\AppData\Roaming\npm\node_modules\npm-windows-upgrade\bin\npm-windows-upgrade
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\<user>\AppData\Roaming\npm\node_modules\npm-windows-upgrade\bin\npm-windows-upgrade'
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\<user>\AppData\Roaming\npm\node_modules\npm-windows-upgrade\bin\npm-windows-upgrade'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\<user>\npm-debug.log
npm ERR! code 1
```

**Comment by dlong500** [comment]
Ah, I see someone just opened a PR to fix this very issue.

**Comment by ihistand** [comment]
This was reproducible for me yesterday, but is now fixed after the latest release. Thanks!

**Comment by felixrieseberg** [comment]
Thanks everyone!

**Comment by dlong500** [comment]
Just curious, I see the new v3.0.1 in NPM, and also see the merged PR, but the package.json in this repo still shows v3.0.0.  Did you publish to NPM from a local repo or something?

**Comment by felixrieseberg** [comment]
Nah, I just didn't push (I made the update from a plane). I'm back on earth though, so it was just poushed!
